# Limites de mais de uma variável

Quando estudamos os [limites no cálculo univariado](limites.qmd), vimos a
importância deste conceito para além de seu papel fundamental na construção
formal do cáculo. Isto é, estudamos como são importantes no estudo do mundo natural,
como na física e química, e até mesmo nas humanidades, como na economia.

Entretanto, poucas coisas na realidade comportam-se apenas com uma única variável.
Por isso, precisamos estender o conceito de limites para funções multivariadas,
e esse será o objetivo desse capítulo.

## Outras formas de dividirmos o domínio
No cálculo de uma variável, costumamos dividir o domínio em duas partes, "à esquerda"
com $\{x: x < a\}$ e "à direita" com $\{x : x > a \}$. Contudo, poderíamos também
dividir o domínio de outras formas. Vamos trabalhar um exemplo

$$
f(x) = \begin{cases}
\sqrt{2}x, x \in \mathbb{Q} \\
x^2, x \in \mathbb{R} \setminus \mathbb{Q}
\end{cases}
$$

*Nota:* $\mathbb{R} \setminus \mathbb{Q}$ significa o conjunto que contém todos 
os números reais que não são racionais

podemos expressar os limites de $x$ se aproximando de um valor arbitrário $a$
como
$$
\begin{aligned}
\lim_{\begin{aligned}x&\rightarrow a \\ x& \in\mathbb{Q}\end{aligned}} f(x) =
\lim_{\begin{aligned}x&\rightarrow a \\ x& \in\mathbb{Q}\end{aligned}} \sqrt{2} x=
\sqrt{2} a \\
\lim_{\begin{aligned}x&\rightarrow a \\ x& \in \mathbb{R}\setminus\mathbb{Q}
\end{aligned}} f(x) =
\lim_{\begin{aligned}x&\rightarrow a \\ x& \in\mathbb{R}\setminus\mathbb{Q}
\end{aligned}} x^2 = a^2
\end{aligned}
$$

Dividindo o domínio em pedaços, temos que
$$
\lim_{x\rightarrow a} f(x) = L \Leftrightarrow
\lim_{\begin{aligned}x&\rightarrow a \\ x& \in\mathbb{R}\setminus\mathbb{Q}
\end{aligned}} f(x) = L = 
\lim_{\begin{aligned}x&\rightarrow a \\ x& \in\mathbb{Q}\end{aligned}}
$$

Para que a igualdade à direita exista, necessitamos que $\sqrt{2}a = a^2$. Assim,
a iguldade vale para $a=0$ e $a=\sqrt{2}$. Logo, $\lim_{x\rightarrow a} f(x)$
existe somente para $a=0$ e $a=\sqrt{2}$! Isso significa que a função é contínua
apenas em $0$ (onde assume o valor de 0) e em $\sqrt{2}$ (onde assume o valor de 2).

Essa técnica de dividir o domínio é muito importante para calcularmos limites
de várias variáveis. Vamos fazer um exemplo

### Calculando limites com duas variáveis

Temos uma função simpels, $f(x) = \frac{x^3y^6}{x^4+y^8}$. Note que essa função
só existe quando $x$ e $y$ são *ambos* diferentes de 0. Mas, se quisermos
descobrir o que acontece na região do $\mathbb{R}^2$ próxima do ponto $(0,0)$,
podemos calcular o seguinte limite:

$$
\lim_{(x,y) \rightarrow (0,0)} \frac{x^3y^6}{x^4+y^8}
$$

Vamos utilizar a técnica anterior e dividir o domínio. Para isso, precisamos
buscar uma relação entre $\lvert x \rvert$ e $\lvert y \rvert$. Tentaremos
encontrar $\alpha > 0$ tal que $\lvert x \rvert \leq \lvert y \rvert^\alpha$ e
$\lvert x \rvert \geq \lvert y \rvert^{\alpha} \Leftrightarrow \lvert y \rvert \leq \lvert x \rvert^{\frac{1}{\alpha}}$

#### Exemplo 1

1. $\lvert x \rvert \leq \lvert y \rvert^{\alpha}$
$$
0 \leq \left\lvert \frac{x^3y^6}{x^4+y^8} \right\rvert = \frac{\lvert x \rvert^3 \lvert y \rvert^6}
{x^4+y^8} \leq \frac{\lvert y \rvert ^{3\alpha} \lvert y \rvert^6}{x^4 + y^8} =
\frac{\lvert y \rvert^{6+3\alpha}}{x^4 + y^8}
$$

Se $6+3\alpha > 8$, temos

$$
\cancelto{0}{\lvert y \rvert^{6+3\alpha-8}} \cdot
\underbrace{\frac{\lvert y \rvert^{8}}{x^4+y^8}}_{\text{Limitado}}
$$

Assim, se $6+3\alpha > 8$, pelo [teorema do confronto](limites.qmd#sec-confronto)

$$
\lim_{\begin{aligned}(x,y)&\rightarrow (0,0) 
\\ \lvert x \rvert &\leq \lvert y \rvert^{\alpha} \end{aligned}} 
\left\lvert \frac{x^3 y^6}{x^4+y^8} \right\rvert = 0 
$$

Portanto,

$$
\lim_{\begin{aligned}(x,y)&\rightarrow (0,0) 
\\ \lvert x \rvert &\leq \lvert y \rvert^{\alpha} \end{aligned}} 
\frac{x^3 y^6}{x^4+y^8} = 0
$$

2. $\lvert x \rvert \geq \lvert y \rvert^{\alpha} \Leftrightarrow \lvert y \rvert \leq \lvert x \rvert^{\frac{1}{\alpha}}$

$$
0 \leq \left\lvert \frac{x^3y^6}{x^4+y^8} \right\rvert = 
\frac{\lvert x \rvert^3 \lvert y \rvert^6}{x^4+y^8} \leq
\frac{\lvert x \rvert^3 \lvert x \rvert^{\frac{6}{\alpha}}}{x^4+y^8}
$$

Se $3 + \frac{6}{\alpha} > 4$, então
$$
\leq \frac{\lvert x \rvert^{3 \frac{6}{\alpha}}}{x^4+y^8} =
\cancelto{0}{\lvert x \rvert^{3 + \frac{6}{\alpha} - 4}} \cdot
\underbrace{\frac{\lvert x \rvert^4}{x^4+y^8}}_{\text{Limitado}}
$$

Para $3 + \frac{6}{\alpha} > 4$ temos pelo [teorema do confronto](limites.qmd$sec-confronto),

$$
\lim_{\begin{aligned}(x,y)&\rightarrow (0,0) \\ 
\lvert x \rvert & \geq \lvert y \rvert^{\alpha} \end{aligned}}
\left\lvert \frac{x^3y^6}{x^4+y^8} \right\rvert = 0
$$

Portanto,

$$
\lim_{\begin{aligned}(x,y)&\rightarrow (0,0) \\ 
\lvert x \rvert & \geq \lvert y \rvert^{\alpha} \end{aligned}}
\frac{x^3y^6}{x^4+y^8}  = 0
$$

Vamos analisar esse número $\alpha$. Sabemos pelo ponto 1. que $6 + 3\alpha - 8 >0$
e pelo ponto 2. que $3 + \frac{6}{\alpha} - 4 >0$.

$$
1. ~~~
\begin{aligned}
  &6 + 3\alpha - 8 > 0 \\
  &\Leftrightarrow 3\alpha > 2 \\
  &\Leftrightarrow \alpha > \frac{2}{3} \\
\end{aligned} ~~~~~~~~
2. ~~~
\begin{aligned}
  &3 + \frac{6}{\alpha} > 4 \\
  &\Leftrightarrow \frac{6}{\alpha} > 1 \\
  &\Leftrightarrow \alpha < 6
\end{aligned}
$$


Dessa forma, para termos os dois limites nessa repartição, vasta considerar
$\alpha$ com $\frac{2}{3}<\alpha<6$. Podemos, por exempo, tomar $\alpha = 1$.
Com isso,

$$
\lim_{\begin{aligned}
(x,y)&\rightarrow(0,0)\\ \lvert x \rvert &\leq \lvert y \rvert
\end{aligned}}
\frac{x^3y^6}{x^4+y^8} = 0 =
\lim_{\begin{aligned}
(x,y)&\rightarrow(0,0)\\ \lvert x \rvert &\geq \lvert y \rvert
\end{aligned}}
\frac{x^3y^6}{x^4+y^8}
$$

Assim, calculamos nosso limite após dividí-lo em relação ao módulo de $x$ e $y$
e obtermos um mesmo valor $L=0$

$$
\lim_{(x,y)\rightarrow(0,0)}
\frac{x^3y^6}{x^4+y^8} = 0
$$

#### Exemplo 2

$$
\lim_{(x,y)\rightarrow (0,0)} \frac{x^3y^3}{x^4+y^8}
$$

Tentaremos novamente dividir o domínio através de uma relação entre o módulo
de $x$ e o módulo de $y$. Isto é, vamos tentar encontrar $\alpha>0$ tal que
$\lvert x \rvert \leq \lvert y \rvert^{\alpha}$ e 
$\lvert x \rvert \geq \lvert y \rvert^{\alpha}$

1. $\lvert x \rvert \leq \lvert y \rvert^{\alpha}$

$$
0 \leq \left\lvert \frac{x^3y^3}{x^4+y^8}\right\rvert
\leq \frac{\lvert y \rvert^{3\alpha}\lvert y \rvert^{3}}{x^4+y^8}
$$

Se $3 \alpha + 3 > 8$

$$
= \cancelto{0}{\lvert y \rvert ^{3\alpha + 3 - 8}} \cdot
\underbrace{\frac{\lvert y \rvert^8}{x^4+y^8}}_{\text{Limitado}} = 0
$$

Se $3 \alpha + 3 > 8$, então pelo [teorema do confronto](limites.qmd$sec-confronto),

$$
\lim_{\begin{aligned}(x,y)\rightarrow (0,0)
\\ \lvert x \rvert \leq \lvert y \rvert^{\alpha}
\end{aligned}} \left\lvert \frac{x^3y^3}{x^4+y^8} \right\rvert = 0
$$

Logo,
$$
\lim_{\begin{aligned}(x,y)\rightarrow (0,0)
\\ \lvert x \rvert \leq \lvert y \rvert^{\alpha}
\end{aligned}} \frac{x^3y^3}{x^4+y^8} = 0
$$

2. $\lvert x \rvert \geq \lvert y \rvert^{\alpha}$, o que é equivalente a
$\lvert y \rvert \leq \lvert x \rvert^{\frac{1}{\alpha}}$

$$
0 \leq \left\lvert \frac{x^3y^3}{x^4+y^8}\right\rvert = 
\frac{\lvert x \rvert^3 \lvert y \rvert^3}{x^4+y^8}
\leq \frac{\lvert x \rvert^3 \lvert x \rvert^{\frac{3}{\alpha}}}{x^4+y^8}
$$

Se $3 + \frac{3}{\alpha} > 4$, temos

$$
= \cancelto{0}{\lvert x \rvert^{3+ \frac{3}{\alpha}-4}} \cdot
\underbrace{\frac{\lvert x \rvert^4}{x^4+y^8}}_{\text{Limitado}} = 0
$$

Assim, se $3 + \frac{3}{\alpha} > 4$, então pelo [teorema do confronto](limites.qmd$sec-confronto),

$$
\lim_{\begin{aligned}(x,y)\rightarrow (0,0)
\\ \lvert x \rvert \geq \lvert y \rvert^{\alpha}
\end{aligned}} \frac{x^3y^3}{x^4+y^8} = 0
$$

$$
1. ~~~
\begin{aligned}
  &3 + 3\alpha - 8 > 0 \\
  &\Leftrightarrow 3\alpha > 5 \\
  &\Leftrightarrow \alpha > \frac{5}{3} \\
\end{aligned} ~~~~~~~~
2. ~~~
\begin{aligned}
  &3 + \frac{3}{\alpha} > 4 \\
  &\Leftrightarrow \frac{3}{\alpha} > 1 \\
  &\Leftrightarrow \alpha < 3
\end{aligned}
$$

Como $3 > \frac{5}{3}$, podemos fixar um $\alpha$ tal que
$$
\frac{5}{3} < \alpha < 3
$$

Vamos usar, por exemplo, $\alpha = 2$. Assim,

$$
\lim_{\begin{aligned}(x,y)\rightarrow (0,0)
\\ \lvert x \rvert \leq \lvert y \rvert^{2}
\end{aligned}} \frac{x^3y^3}{x^4+y^8} = 0 = 
\lim_{\begin{aligned}(x,y)\rightarrow (0,0)
\\ \lvert x \rvert \geq \lvert y \rvert^{2}
\end{aligned}} \frac{x^3y^3}{x^4+y^8}
$$

#### Exemplo 3
$$
\lim_{(x,y)\rightarrow(0,0)} \frac{x^3y^2}{x^4+y^8}
$$

1. $\lvert x \rvert \leq \lvert y \rvert^{\alpha}$

$$
0 \leq \left\lvert\frac{x^3 y^2}{x^4+y^8} \right\rvert=
\frac{\lvert x \rvert^3 \lvert y \rvert^2}{x^4+y^8} \leq
\frac{\lvert y \rvert^{3\alpha} \lvert y \rvert^2}{x^4+y^8} \\
$$

Se $3\alpha + 2 > 8$,

$$
\leq \cancelto{0}{\lvert y \rvert^{3\alpha+2-8}}
\underbrace{\frac{\lvert y \rvert^{8}}{x^4+y^8}}_{\text{Limitado}} = 0
$$

Para $3\alpha + 2 > 8$, pelo teorema do confronto, temos
$$
\lim_{\begin{aligned}(x,y)&\rightarrow (0,0) \\ 
\lvert x \rvert & \leq \lvert y \rvert^{\alpha} \end{aligned}}
\left\lvert \frac{x^3y^2}{x^4+y^8} \right\rvert = 0 \Rightarrow
\lim_{\begin{aligned}(x,y)&\rightarrow (0,0) \\ 
\lvert x \rvert & \leq \lvert y \rvert^{\alpha} \end{aligned}}
\frac{x^3y^2}{x^4+y^8} = 0
$$

2. $\lvert x \rvert \geq \lvert y \rvert^{\alpha} \Leftrightarrow \lvert y \rvert \leq \lvert x \rvert^{\frac{1}{\alpha}}$

$$
0 \leq \left\lvert\frac{x^3y^2}{x^4+y^8} \right\rvert=
\frac{\lvert x \rvert^3 \lvert y \rvert^2}{x^4+y^8} \leq
\frac{\lvert x \rvert^{3} \lvert x \rvert^{\frac{2}{\alpha}}}{x^4+y^8} \\
$$

Se $3 + \frac{2}{\alpha} > 4$,

$$
\leq \cancelto{0}{\lvert x \rvert^{3+\frac{2}{\alpha}-4}}
\underbrace{\frac{\lvert x \rvert^{4}}{x^4+y^8}}_{\text{Limitado}} = 0
$$

Para $3 + \frac{2}{\alpha}$ temos pelo teorema do confronto,

$$
\lim_{\begin{aligned}(x,y)&\rightarrow (0,0) \\ 
\lvert x \rvert & \geq \lvert y \rvert^{\alpha} \end{aligned}}
\left\lvert \frac{x^3y^2}{x^4+y^8} \right\rvert = 0 \Rightarrow
\lim_{\begin{aligned}(x,y)&\rightarrow (0,0) \\ 
\lvert x \rvert & \geq \lvert y \rvert^{\alpha} \end{aligned}}
\frac{x^3y^2}{x^4+y^8} = 0
$$

$$
1. ~~~
\begin{aligned}
  &3\alpha + 2 > 8 \\
  &\Leftrightarrow 3\alpha > 6 \\
  &\Leftrightarrow \alpha > 2 \\
\end{aligned} ~~~~~~~~
2. ~~~
\begin{aligned}
  &3 + \frac{2}{\alpha} > 4 \\
  &\Leftrightarrow \frac{2}{\alpha} > 1 \\
  &\Leftrightarrow \alpha < 2
\end{aligned}
$$

Como não existe um número $\alpha$ tal que $2 < \alpha < 2$, não podemos usar
essa estratégia para concluir se o limite existe e falhamos em satisfazer as desigualdades
para $\alpha = 2$

Vamos tentar outra estratégia usando $x = y^2$, parametrizando uma curva
$\gamma(t)=(t^2,t) \Rightarrow \gamma(0) = (0,0)$

$$
\lim_{t\rightarrow 0} f \circ \gamma (t) = \lim_{t\rightarrow 0}
\frac{t^6 t^2}{t^8 + t^8} = \lim_{t\rightarrow 0} \frac{t^8}{2t^8} = \frac{1}{2}
$$

Vamos testar outra curva e conferir se temos um resultado único entre elas
$\phi(t) = (0,t) \Rightarrow \phi(0) = (0,0)$

$$
\lim_{t\rightarrow 0} f \circ \phi (t) = \lim_{t\rightarrow 0} \frac{0^3 t^2}{0^4+t^8} = 0
$$

Como $\lim_{t\rightarrow 0} f \circ \gamma (t) \neq \lim_{t\rightarrow 0} f \circ \phi(t)$,
segue que esse $\lim_{(x,y)\rightarrow (0,0)} f(x,y)$ não existe.

Note que essa estratégia é útil para demonstrar que certos limites não existem,
mas caso o limite exista, teríamos que testar infinitas curvas para provar sua existência?

#### Exemplo 4

$$
\lim_{(x,y) \rightarrow (0,0)} \frac{x^3 y^2}{x-y}
$$

Neste exemplo temos que o denominador zera num conjunto que se acumula em (0,0).
Assim para mostrar que o limite não existe, vamos nos aproximar rapidamente do conjunto
$\{(x,y):x-y =0\}$. Para que o denominador vá para $0$ mais rápido do que o numerador.

Uma parametrização desse conjunto pode ser dada por $(t,t)$. Como não queremos
"andar" sobre $\{(x,y):x-y =0\}$, tomaremos $\gamma_n (t) = (t+t^n,t)$, assim o
denominador vai rapido para 0 dependendo de $n$, pois $t+t^n-t = t^n$.

Para isto, $n>0$, então

$$
\begin{aligned}
\lim_{t\rightarrow 0} f \circ \gamma_{n}(t) &= \lim_{t\rightarrow 0}
\frac{(t+t^n)^3t^2}{t+t^n-t} \\
\lim_{t\rightarrow 0} \frac{t^3 (1+t^{n-3})t^2}{t^n}
\lim_{t\rightarrow 0} \frac{t^5 (1+t^{n-3})}{t^n}
\lim_{t\rightarrow 0} \frac{(1+t^{n-3})}{t^{n-5}}
\end{aligned}
$$

Pelo nuemrador, vemos que precisamos de $n\geq 3$. Pelo denominador, precisamos
de $n \geq 5$.

$$
\lim_{t\rightarrow 0} f\circ \gamma_5 (t) = \lim_{t\rightarrow 0} \frac{1+t^2}{1} = 1
$$

$$
\lim_{t\rightarrow 0} f\circ \gamma_6 (t) = \lim_{t\rightarrow 0} \frac{1+t^3}{t} = +\infty
$$

assim, como esses limites são diferentes, não existe
$$
\lim_{(x,y)\rightarrow(0,0)} f(x,y)
$$

Neste exercício, observamos um potencial ponto falho que abriria um caminho para
mostrar que o limite não existe (nesse caso, o denominador), e utilizamos uma estratégia
para encontrar curvas que demonstrassem isso.

#### Exemplo 5

$$
\lim_{(x,y)\rightarrow(0,0)} \frac{x^4 y^9}{x^2-y^5} = f(x,y)
$$

$(t^\frac{1}{2}, t^{\frac{1}{5}}), t > 0$ parametriza $\{(x,y):x^2-y^5=0, x>0, y>0\}$

Vamos usar $\gamma_n(t) = \left((t+t^n)^{\frac{1}{2}}, t^{\frac{1}{5}}\right), \gamma_n(0) = (0,0)$
novamente com a ideia de manter um denominador que fica pequeno dependendo de $n$
atraveś de $((t+t^n)^{\frac{1}{2}})^2 - (t^{\frac{1}{5}})^5 = t+t^n -t = t^n$.

$$
\begin{aligned}
\lim_{t\rightarrow 0} f \circ \gamma_n(t) &= \lim_{t\rightarrow 0}
\frac{\left((t+t^n)^{\frac{1}{2}}\right)^4 (t^\frac{1}{5})^9}{t^n} \\
& = \lim_{t\rightarrow 0} \frac{(t+t^n)^2 t^{\frac{9}{5}}}{t^n} \\
& = \lim_{t\rightarrow 0} \frac{t^2 (1+t^{n-1})^2 t^{\frac{9}{5}}}{t^n} \\
& = \lim_{t\rightarrow 0} \frac{(1+t^{n-1})^2}{t^{n-2-\frac{9}{5}}}
\end{aligned}
$$

Pelo numerador, precisamos de $n \geq 1$. pelo denominador, precisamos de $n \geq \frac{19}{5}$.
Vamos usar $n = 4$,

$$
\lim_{t\rightarrow 0^{+}} f \circ \gamma_4(t) = \lim_{t\rightarrow 0^{+}}
\frac{(1+t^3)^2}{t^{4-\frac{19}{5}}} = +\infty
$$

Vamos usar outra curva para verificar o limite: $\phi(t) = (t,0) \Rightarrow \phi(0) = (0,0)$

$$
\lim_{t\rightarrow 0} f \circ \phi (t) = \lim_{t \rightarrow 0} \frac{t^4 0^9}{0^2 -t^5} 
= \lim_{t\rightarrow 0} \frac{0}{-t^5} = 0
$$

Assim, $\lim_{t\rightarrow 0} f \circ \gamma_4(t) \neq \lim_{t\rightarrow 0} f \circ \phi (t)$.

Portanto, $\lim_{(x,y) \rightarrow (0,0)} f(x,y)$ não existe.



