# Limites

## Um conceito intuitivo

Você provavelmente já se encontrou com limites ao longo do ensino médio e até mesmo fundamental e, em sua ingenuidade,
nem percebeu. Duvida? Um exemplo simples.

Provavelmente enquanto aprendia divisão, especialmente envolvendo frações, você se deparou com a dúvida universal "O
que acontece quando dividimos por $0$?". Ainda nesse cenário, seu professor pode ter pedido que você perguntasse à
calculadora, em que você teria a triste resposta "erro", ou em casos mais interessantes, $\infty$. O que está acontecendo
aqui?

Intuitivamente, sabemos que, quanto maior o divisor, menor será o quociente. Quando começamos a aprender frações e
desbloqueamos o mundo mágico em que o resto da divisão passa a importar, também percebemos que, quando dividimos um
número por outro menor que $1$, obtemos um quociente maior que nosso dividendo:

$$
\frac{1}{1} = 1,\; \frac{1}{0.5} = 2,\; \frac{1}{0.25} = 4,\; \frac{1}{0.01} = 100,\; \dots ?
$$

Mas e o que acontece se continuamos diminuindo nosso divisor? Claro, caso seja um número menor que $0$, temos resultados
simétricos aos positivos, mas o que acontece quando chegamos cada vez mais perto de $0$?

$$
\frac{1}{x\rightarrow 0} = ?
$$

Da mesma forma, e se pegarmos números cada vez maiores no divisor? Sabemos que quanto maior o divisor, menor o número,
mas existe algum limiar, algum *limite* de quão pequeno esse número pode ser? Chegaria algum momento que cairíamos de
ponta-cabeça nos números negativos, ou há algo nos barrando de descer "para o outro lado" da reta real?

$$
\frac{1}{x\rightarrow \infty} = ?
$$

``` {.tikz width=100%}
%%| format: tex
%%| filename: limite1divx
%%| fig-cap: $f(x) = \frac{1}{x}$
\begin{tikzpicture}
  \begin{axis}[xmin=-4.2,xmax=4.2,ymin=-6.2, ymax=6.2,
      axis lines = middle,
      xlabel= $x$,
    ylabel= $\frac{1}{x}$]
    \addplot[color=red, samples = 500, domain=-4.2:-0.001]{1/x};
    \addplot[color=red, samples = 500, domain=0.001:4.2]{1/x};
  \end{axis}
\end{tikzpicture}
```

Para responder essas e outras perguntas importantes sobre o comportamento de funções, partimos para o estudo formal
de limites.

## Limites e continuidade

Você provavelmente já ouviu a "definição" querida pelos professores para funções contínuas. Uma função é contínua, claro,
se, e somente se, podemos desenhá-la sem tirar o lápis do papel!

Deixando as brincadeiras de lado, há certa verdade nessa interpretação. Considere a seguinte função de domínio e contradomínio reais,
isto é, $f : \mathbb{R} \rightarrow \mathbb {R}$:
$$
f(x) =\left\{\begin{array}{ll}
1, & \mathrm{se}\ x < 1 \\
2, & \mathrm{se}\ x \geq 1
\end{array}\right.
$$

Antes de ver o gráfico, tente pensar um pouco se essa função é contínua para todo $x$ real. Exite algum ponto com "salto",
ou que a função não está bem definida?

```{.tikz width=100%}
%%| format: tex
%%| filename: limitefuncaochave1
%%| fig-cap: Função chave
\begin{tikzpicture}
  \begin{axis}[xmin=0,xmax=4,ymin=0, ymax=4,
      axis lines = left,
      xlabel= $x$,
    ylabel= $f(x)$]
    \draw(0,1) -- (0.95,1);
    \draw(1,1) circle[radius=0.05];
    \draw(1,2) -- (4,2);
    \draw(1,2) circle[radius=0.05];
    \fill[black](1,2) circle [radius=0.05];
    \fill[white](1,1) circle [radius=0.05];
  \end{axis}
\end{tikzpicture}
```

Do gráfico, vemos que a função não é contínua no ponto $x=1$, mas é contínua em todos os outros pontos da reta real.

Algumas funções são mais enganosas. Vamos considerar $f : \mathbb{R} \rightarrow \mathbb{R}$:
$$
f(x) =\left\{\begin{array}{ll}
x, & \mathrm{se}\ x \neq 2 \\
1, & \mathrm{se}\ x = 2
\end{array}\right.
$$

```{.tikz width=100%}
%%| format: tex
%%| filename: limitefuncaochave2
%%| fig-cap: Ponto de descontinuidade numa função chave
%%| fig-label: fig-enganosa
\begin{tikzpicture}
  \begin{axis}[xmin=0,xmax=4,ymin=0, ymax=4,
      axis lines = left,
      xlabel= $x$,
    ylabel= $f(x)$]
    \draw(0,0) -- (2,2);
    \draw(2,2) circle[radius=0.05];
    \draw(2,2) -- (4,4);
    \draw(2,1) circle[radius=0.05];
    \draw[dash dot](2,1.05) -- (2,1.95);
    \fill[black](2,1) circle [radius=0.05];
    \fill[white](2,2) circle [radius=0.05];
  \end{axis}
\end{tikzpicture}
```

Essa "função enganosa" nos mostra algo curioso: se nos aproximamos de $x=2$, a função se aproxima de $2$, isto é,
$$
f(x) \stackrel{x\rightarrow 2}{\rightarrow} 2,
$$
por outro lado,
$$
f(2) = 1.
$$

De fato, o valor que se espera que a função tenha no ponto $x$ é o conceito intuitivo de limite! Podemos escrever que o
limite $L$ da função $f(x)$ conforme $x$ se aproxima de $2$ é $2$:
$$
\lim_{x\rightarrow 2} f(x) = L = 2 \neq f(2).
$$

Disso, temos uma definição *formal* de continuidade:

::: {.callout-note title="Definição de continuidade"}
Uma função é dita ser contínua no ponto $x_0$ se, e somente se,
$$
\lim_{x\rightarrow x_0} f(x) = f(x_0).
$$
:::

Com essa definição, conseguimos afirmar que nossa função enganosa não é contínua no ponto $x=2$.

Vamos experimentar calculando alguns limites! 

$$
\begin{aligned}
\lim_{x \rightarrow 0} \frac{x^2}{x} &= \lim_{x\rightarrow 0} x = 0 \\
\lim_{x\rightarrow 1} \frac{x^2 - 1}{x - 1} &= \lim_{x\rightarrow 1} \frac{(x+1)(x-1)}{(x-1)} = \lim_{x\rightarrow 1} x+1 = 2
\end{aligned}
$$

::: {.callout-tip title="Lidando com indefinições"}
Como estratégia, queremos simplificar as expressões o máximo possível, buscando eliminar indefinições,
antes de calcularmos o valor limite.

Nos exemplos acima, não poderíamos substituir o valor de $x$ diretamente antes de resolvermos o limite, ou estaríamos
dividindo por 0, um crime!
:::

Nem sempre é possível lidar com as indeterminações. Trataremos delas posteriormente, mas você já pode pensar em que
acontece quando nos aproximamos de monstruosidades como a divisão por $0$.

## Formalizando limites

Nosso objetivo nessa seção é tentar entender o seguinte:

::: {.callout-note title="Definição de limite"}
Seja $f$ uma função e $a$ um ponto no domínio (ou extremidade do domínio) de $f$, $D_f$. Dizemos que $f$ tem limite $L$
no ponto $a$ se, e somente se, para todo $\epsilon>0$ fixo, existe um $\delta > 0$ tal que para todo $x$ em $D_f$,
$$
0 < | x-a | < \delta \Rightarrow | f(x) - L | < \epsilon.
$$

Quando existe, esse $L$ é único e escrevemos $\lim\limits_{x \rightarrow a}f(x) = L$.
:::

Que confusão! Tentaremos entender em outras palavras, ou melhor, desenhando! Vamos considerar uma função simples, como
$f(x) = x$. Com uma relação entre $a$ e $\delta$, esperamos escrever $\delta$ no eixo $x$, enquanto
$\epsilon, L$, por se relacionarem com o valor da função, $f(x)$, estarão descritos no outro eixo:


```{.tikz width=100%}
%%| format: tex
%%| filename: limiteidentidadedef
%%| fig-cap: Visualizando a definição de limites
\begin{tikzpicture}
  \begin{axis}[
      xmin=0, xmax=4,
      ymin=0, ymax=4,
      axis lines=left,
      xlabel=$x$,
      ylabel=$f(x)$,
      clip=false, % Disable clipping to render nodes outside the axis
      %after end axis/.code={ % Optional: Re-clip the main plot area
      % (keeps lines/curves clean)
      %  \path[clip] (current axis.south west) rectangle (current
      % axis.north east);
      %} % This is needed for examples where curves and plots might
      % extend over the axis.
      xtick=\empty,
      ytick=\empty,
      xlabel style={
        font=\scriptsize,     % Smaller font
        at={(axis description cs:1,0)}, % Position at end of x-axis
        anchor=north east,    % Anchor to align near the arrow tip
        xshift=-2pt           % Fine-tune horizontal position
      },
      ylabel style={
        font=\scriptsize,     % Smaller font
        at={(axis description cs:0,1)}, % Position at end of y-axis
        anchor=south east,    % Anchor to align near the arrow tip
        yshift=2pt            % Fine-tune vertical position
      },
    ]

    \draw (0,0) -- (4,4);

    % Hatched area
    \fill[pattern=north east lines, pattern color=gray] (1.5,1.5)
    rectangle (2.5,2.5);

    % Y-axis
    \draw[dash dot] (0,1.5) node[left, xshift=-2pt] {$L - \epsilon$} -- (4,1.5);
    \draw[dotted] (0,2) node[left, xshift=-2pt] {$L$} -- (2,2);
    \draw[dash dot] (0,2.5) node[left, xshift=-2pt] {$L + \epsilon$} -- (4,2.5);

    % X-axis
    \draw[dash dot] (1.5,0) node[below, yshift=-2pt] {$a + \delta$} -- (1.5,4);
    \draw[dotted] (2,0) node[below, yshift=-2pt] {$a$} -- (2,2);
    \draw[dash dot] (2.5,0) node[below, yshift=-2pt] {$a - \delta$} -- (2.5,4);

    \draw(2,2) circle[radius=0.03]
    \fill[black](2,2) circle [radius=0.03];

  \end{axis}
\end{tikzpicture}
```

Nosso objetivo é verificar e é possível "comprimir" essa área até o ponto $f(a)$. Caso consigamos, podemos dizer que $L$
é o limite de $f$ no ponto $a$. Sabemos que, como $f(x) = x$ é uma função contínua, esse limite $L$ existe no ponto $a$
e é o próprio valor da função neste ponto, $f(a) = a$. Consideraremos novamente nossa [função enganosa](#fig-enganosa)
e visualizaremos que seu limite no ponto $2$ é $2$.

Vamos assumir, por absurdo, que $L = 1$, ou seja, que o limite no ponto $a=2$ da função enganosa seja na verdade $1$.
Note que, mesmo escolhendo um valor muito pequeno para $\delta$, não satisfazeriamos as condições para um $\epsilon$
pequeno!

```{.tikz width=100%}
%%| format: tex
%%| filename: limitedefEnganosa
%%| fig-cap: Visualizando a definição na "função enganosa"
\begin{tikzpicture}
  \begin{axis}[
      xmin=0, xmax=4,
      ymin=0, ymax=4,
      axis lines=left,
      xlabel=$x$,
      ylabel=$f(x)$,
      clip=false, % Disable clipping to render nodes outside the axis
      %after end axis/.code={ % Optional: Re-clip the main plot area
      % (keeps lines/curves clean)
      %  \path[clip] (current axis.south west) rectangle (current
      % axis.north east);
      %} % This is needed for examples where curves and plots might
      % extend over the axis.
      xtick=\empty,
      ytick=\empty,
      xlabel style={
        font=\scriptsize,     % Smaller font
        at={(axis description cs:1,0)}, % Position at end of x-axis
        anchor=north east,    % Anchor to align near the arrow tip
        xshift=-2pt           % Fine-tune horizontal position
      },
      ylabel style={
        font=\scriptsize,     % Smaller font
        at={(axis description cs:0,1)}, % Position at end of y-axis
        anchor=south east,    % Anchor to align near the arrow tip
        yshift=2pt            % Fine-tune vertical position
      },
    ]

    \draw (0,0) -- (1.5,1.5);
    \draw (2.5,2.5) -- (4,4);

    % Hatched area
    \fill[pattern=north east lines, pattern color=gray] (1.5,0.5)
    rectangle (2.5,1.5);

    % Y-axis
    \draw[dash dot] (0,0.5) node[left, xshift=-2pt] {$L - \epsilon$} -- (4,0.5);
    \draw[dotted] (0,1) node[left, xshift=-2pt] {$L$} -- (2,1);
    \draw[dash dot] (0,1.5) node[left, xshift=-2pt] {$L + \epsilon$} -- (4,1.5);

    % X-axis
    \draw[dash dot] (1.5,0) node[below, yshift=-2pt] {$a + \delta$} -- (1.5,4);
    \draw[dotted] (2,0) node[below, yshift=-2pt] {$a$} -- (2,2);
    \draw[dash dot] (2.5,0) node[below, yshift=-2pt] {$a - \delta$} -- (2.5,4);

    \draw[color=red, dashed] (1.5,1.5) -- (2.5,2.5);
    \node[align=center, color=red] at (2,2.6) {\tiny$|L - f(x)| > \epsilon$}
    \draw(2,2) circle[radius=0.03]
    \fill[white](2,2) circle [radius=0.03];

    \draw(2,1) circle[radius=0.03];
    \fill[black](2,1) circle [radius=0.03];

  \end{axis}
\end{tikzpicture}
```

Dessa forma, toda a seção em vermelho (tracejada) não obedece $|f(x) - L| < \epsilon$ para pelo menos algum $\epsilon$,
logo, esse valor de $L$ não pode ser o limite nesse ponto desta função! Tente desenhar e observar que o limite intuitivo
dessa função no ponto $x=2$ é de fato $2$ pela definição.



A definição formal não nos ajuda muito a encontrar limites, mas podemos confirmar nossa intuição usando essa formalidade.
Tomemos o exemplo acima. Para deixar mais claro a relação de implicação, podemos também escrever

$$
|f(x) - L| < \epsilon \text{ quando } |x-2| < \delta
$$

Substituindo os valores de $L$ (queremos testar se $L=2$ é o limite neste ponto) e $f(x) =x$,

$$
|x - 2| < \epsilon \text{ quando } |x-2| < \delta
$$

<!-- TODO: Criar uma seção de lógica? (e linkar aqui) -->
Uma vez que para todo $\epsilon$ podemos escolher $\delta = \epsilon$, isso é sempre verdade
(algo implicar si mesmo é uma [tautologia](https://pt.wikipedia.org/wiki/Tautologia_(l%C3%B3gica))!). Logo, podemos afirmar
que, pela definição, $\lim\limits_{x\rightarrow2}f(x) = 2$.

Partiremos para outra função, como $f(x) = x^2$, para aprendermos a manipular um pouco as expressões e verificar o
limite.

Sabemos que $x^2$ é uma função contínua, logo, qualquer valor da função será seu limite nesse ponto. Verificaremos esse
fato usando a definição para o ponto $x=0$.

$$
\begin{aligned}
|f(x) - L| < \epsilon &\text{ quando } |x-0| < \delta \\
|x^2 - 0| < \epsilon &\text{ quando } |x-0| < \delta \\
|x^2| < \epsilon &\text{ quando } |x| < \delta \\
|x| < \sqrt{\epsilon} &\text{ quando } |x| < \delta \\
\end{aligned}
$$

Logo, com $\delta = \sqrt{\epsilon}$, verificamos que o limite de $f(x) = x^2$ quando $x$ se aproxima de $0$ é, como
esperávamos pela continuidade, $0$.

Contudo, até em verificar nossa intuição a definição pode ser de pouca ajuda. No exemplo anterior, caso escolhêssemos
o ponto $a=1$, aplicar a definição seria um pouco mais complicado (tente você mesmo!). Por isso, como veremos na próxima
seção, grande parte da importância da definição formal de limites está em fornecer ferramentas para facilitar o cálculo
desses limites.

Ainda assim, existem diversas técnicas que trabalhamos na resolução de limites.
Considere a função

$$
f(x) = \frac{x^4 + x^2 + x}{x^5 + x^4 + 3x}
$$

Quando $x\rightarrow 0$, ambos o denominador e numerador tendem a 0. Ainda
assim, o valor do limite pode não ser claro, ainda assim, existe. Tente plotar a
função para verificar isto!

Uma forma de resolver este limite é simplesmente simplificando a fração:

$$
\lim_{x\rightarrow 0} \frac{x^4 + x^2 + x}{x^5 + x^4 + 3x} = 
\lim_{x\rightarrow 0} \frac{x}{x} \frac{x^3 + x + 1}{x^4 + x^3 + 3} =
\frac{1}{3}.
$$

Contudo, nem sempre isto é simples. Considere uma função similar:

$$
f(x) = \frac{x^4 + x^2 + x - 1}{x^5 + x^4 + 3x + 3}
$$

Quando $x\rightarrow -1$, temos que ambos o denominador e numerador tendem a
$0$. Uma pergunta natural é descobrir qual o limite da função neste ponto:

$$
\lim_{x\rightarrow -1} \frac{x^4 + x^2 + x - 1}{x^5 + x^4 + 3x + 3} = ?
$$

Plotando essa função, conseguimos ver que este limite, aparentemente, existe.
Mas encontrá-lo com técnicas simples não é trivial (você consegue encontar
alguma forma de simplificar isso, como fizemos anteriormente?). Bem
posteriormente, quando tratarmos de derivadas, desenvolveremos técnicas mais
sofisticadas para resolver limites deste tipo.


## Propriedades importantes dos limites

<!-- TODO: além da continuidade, limite de continua "passa pra dentro", limite do módulo, limite de -f, etc. -->

1) Se $g$ é uma função contínua, então $\lim\limits_{x\rightarrow a} g(f(x)) = g(\lim\limits_{x\rightarrow a} f(x))$

2. Se $\lim\limits_{x\rightarrow a} f(x) = L_1, \lim\limits_{x\rightarrow a} g(x) = L_2, L_1, L_2 \in \mathbb{R}$, então:
    1. $\lim\limits_{x\rightarrow a} (f(x) + g(x)) = L_1 + L_2$
    2. $\lim\limits_{x\rightarrow a} kf(x) = kL_1, k \in \mathbb{R}$ (isso é especialmente útil com $k=-1$, o que permite que 2.1. se aplique também em subtrações!
    3. $\lim\limits_{x\rightarrow a} (f(x) \cdot g(x)) = L_1 \cdot L_2$
    4. $\lim\limits_{x\rightarrow a} \frac{f(x)}{g(x)} = \frac{f(x)}{g(x)}, L_2 \neq 0$


## Limites laterais

Retomaremos a função com partes

$$
f(x) = \begin{cases}
1, & \mathrm{se}\ x < 1 \\
2, & \mathrm{se}\ x \geq 1
\end{cases}
$$

E seu gráfico
```{.tikz width=100%}
%%| format: tex
%%| filename: limitefuncaochave1
%%| fig-cap: Função chave
\begin{tikzpicture}
  \begin{axis}[xmin=0,xmax=4,ymin=0, ymax=4,
      axis lines = left,
      xlabel= $x$,
    ylabel= $f(x)$]
    \draw(0,1) -- (0.95,1);
    \draw(1,1) circle[radius=0.05];
    \draw(1,2) -- (4,2);
    \draw(1,2) circle[radius=0.05];
    \fill[black](1,2) circle [radius=0.05];
    \fill[white](1,1) circle [radius=0.05];
  \end{axis}
\end{tikzpicture}
```

Uma pergunta surge naturalmente, qual o limite dessa função quando $x$ se
aproxima de $1$?

Analisando o gráfico, não conseguimos uma resposta óbvia. Seria $2$, pois é o
valor real da função? Seria $1$, pois seguimos a ordem crescente do $x$? Que tal
$1.5$, para uma média entre os dois?

Na verdade, a resposta é que *não existe limite neste ponto* para essa função.
Pelo menos, não um limite *bilateral*. Logo, precisaremos analisar a função de
dois lados distintos: "pela direita" e "pela esquerda"!

Analisando o gráfico, quando o $x$ se aproxima pela esquerda, isto é, valores
crescentes de $x$, temos que
$$
\lim_{x \rightarrow 1^{-}} f(x) = 1
$$
enquanto pela direita, ou seja, valores decrescentes de $x$, temos que
$$
\lim_{x \rightarrow 1^{+}} f(x) = 2
$$

```{.tikz width=100%}
%%| format: tex
%%| filename: limitefuncaochavelaterais
%%| fig-cap: Limites laterais na função chave
\begin{tikzpicture}
  \begin{axis}[xmin=0,xmax=4,ymin=0, ymax=4,
      axis lines = left,
      xlabel= $x$,
    ylabel= $f(x)$]
    \draw(0,1) -- (0.95,1);
    \draw(1,1) circle[radius=0.05];
    \draw(1,2) -- (4,2);
    \draw(1,2) circle[radius=0.05];
    \fill[black](1,2) circle [radius=0.05];
    \fill[white](1,1) circle [radius=0.05];
    \node[align=center, color=red] at (1.5,2.2) {$\leftarrow^+$};
    \node[align=center, color=red] at (0.5,0.8) {$\rightarrow^-$};
  \end{axis}
\end{tikzpicture}
```

Note que o limite lateral pela direita coincide com a função no ponto. Isso
significa que a função é contínua neste ponto? Não! Para haver continuidade,
deve existir o limite completo, bilateral.

:::{.callout-note title="Notação"}
Usamos os símbolos de $+$ e $-$ no mesmo lugar que ficaria um expoente para 
indicarmos a direção do limite.

Limite lateral a esquerda ou pela esquerda no ponto $a$
$$
\lim_{x \rightarrow a^{-}} f(x) = L^-
$$

Limite lateral a direita ou pela direita no ponto $a$
$$
\lim_{x \rightarrow a^{+}} f(x) = L^+
$$
:::

## Limites no infinito e infinitos

Uma das maiores utilidades dos limites é tratar indefinições. Com eles, podemos
estudar o comportamento de funções como $f(x) = 1/x$ próximo a pontos que
costumávamos evitar, como, neste caso $x=0$.

Se voltarmos ao início do capítulo, em que discutimos o conceito intuitivo de
limites usando esta mesma função como exemplo, conseguimos agora, após
formalizarmos um pouco mais nosso raciocínio, dizer que
$$
\lim_{x\rightarrow 0} f(x) = \lim_{x \rightarrow 0} \frac{1}{x}
$$
não existe, uma vez que, pela esquerda, vamos para valores cada vez menores da
função conforme nos aproximamos de $0$, e, pela direita, para valores cada vez
maiores. Usando nossa discussão sobre limites laterais, podemos explorar
$$
\lim_{x\rightarrow 0^-}\frac{1}{x}\ \ \text{e}\ \ \lim_{x\rightarrow 0^+}\frac{1}{x}.
$$

A realidade é que estes valores ainda não "existem", pelo menos não como números
reais! Tomano o limite à esquerda, por exemplo, conforme nos aproximamos de $0$,
o valor da função decresce até valores (absolutos) exorbitantemente grandes:
$$
\frac{1}{-1} = -1,\ \frac{1}{0.1} = -10,\ \dots \, \frac{1}{1 \cdot 10^{-100}} =
-1 \cdot 10^{100}
$$

Quando finalmente chegarmos no $0$, portanto, estaremos em um valor
inimaginavelmente grande, na verdade, é tão incompreensível que sequer podemos
chamá-lo de número. Para representar esse conceito, usamos o símbolo $\infty$,
"Infinito". Nesse caso, como estamos em valores negativos, temos que
$$
\lim_{x\rightarrow 0^-} \frac{1}{x} = -\infty.
$$

Analogamente,
$$
\lim_{x\rightarrow 0^+} \frac{1}{x} = \infty.
$$

Como
$$
\lim_{x\rightarrow 0^-} \frac{1}{x} \neq \lim_{x \rightarrow 0^+},
$$
o limite em si não existe, apenas suas formas laterais.

Uma função próxima, como $f(x) = \frac{1}{x^2}$, terá limite no infito pois
lidamos com o sinal:

``` {.tikz width=100%}
%%| format: tex
%%| filename: limite1divx2
%%| fig-cap: $f(x) = \frac{1}{x^2}$
\begin{tikzpicture}
  \begin{axis}[xmin=-4.2,xmax=4.2,ymin=-0.5, ymax=128,
      axis lines = middle,
      xlabel= $x$,
    ylabel= $\frac{1}{x^2}$]
    \addplot[color=red, samples = 500, domain=-4.2:-0.001]{1/x^2};
    \addplot[color=red, samples = 500, domain=0.001:4.2]{1/x^2};
  \end{axis}
\end{tikzpicture}
```

$$
\lim_{x\rightarrow 0^-} \frac{1}{x^2} = \lim_{x\rightarrow 0^+} \frac{1}{x^2} = \infty.
$$

Podemos também analisar limites quando o próprio $x$ tende a infinito. Sabemos
que

$$
\lim_{x\rightarrow 0} \frac{x}{x} = \lim_{x\rightarrow 0} 1 = 1.
$$

Isso não muda quando tendemos $x$ à infinito, apesar do sinal:
$$
\lim_{x\rightarrow -\infty} \frac{x}{x} = \lim_{x\rightarrow -\infty} 1 = 1.
$$
isso ocorre pois se trata de uma função constante igual a 1. Dessa forma, mesmo
nos infinitos, seu limite ainda é o mesmo em todo ponto da reta real. Por outro
lado, podemos analisar valores como

$$
\lim_{x\rightarrow \infty} \frac{1}{x} = ?
$$

Se pensarmos neste caso como simétrico a quando $x$ tende a $0$, obtemos um
resultado intuitivo:
$$
\lim_{x\rightarrow \infty} \frac{1}{x} = 0
$$

Esperamos esse resultado uma vez que, quanto maior o valor absoluto (em módulo)
do denominador, menor o valor absoluto da fração. Neste sentido, com um
denominador inimaginavelmente grande, o valor absoluto da fração será o menor
possível, 0. Use uma plataforma como o Desmos para esboçar este gráfico e
verificar esse comportamento! Neste caso, como $f(x)$ se aproxima cada vez mais
do eixo $x$, de 0, mas sem tocá-la (lembre-se que infinito é um conceito, não um
número, logo não pode ser alcançado), chamamos o eixo $x$ neste caso de reta
assintota da função. Note que, como analisamos no caso de $x\rightarrow0$, o
eixo $y$ também é uma assintota desta função!

Com essa análise, podemos resolver limites que antes nos pareciam um pouco
assustadores, vamos retomar a função

$$
f(x) = \frac{x^4 + x^2 + x}{x^5 + x^4 + 3x}
$$

Dessa vez, analisaremos $x\rightarrow \infty$, temos que ambos o denominador e
numerador tendem a $\infty$. Contudo, como Podemos observar em um gráfico da
função (você plotou o gráfico, não plotou?), o valor da função não tende a
infinito! Por quê?

A técnica utilizada para resolver este limite é pelo majorante. Isto é,
buscaremos o termo dominante nesta expressão ao analisarmos os polinômios no
numerador e denominador. Faremos isso fatorando $\frac{x^4}{x^4}$:

$$
\lim_{x\rightarrow \infty} \frac{x^4 + x^2 + x}{x^5 + x^4 + 3x} =
\lim_{x\rightarrow \infty} \frac{x^4}{x^4} \frac{1 + \frac{1}{x^2} + \frac{1}{x^3}}
{x + 1 + \frac{3}{x^3}} =
\lim_{x\rightarrow \infty} \frac{1 + \frac{1}{x^2} + \frac{1}{x^3}}
{x + 1 + \frac{3}{x^3}}
$$

Como $\lim\limits_{x\rightarrow \infty} \frac{1}{x^a} = 0, \forall a > 0$, temos que o
numerador vai para 1 enquanto o denominador vai para $\infty$, o useja, o limite
é 0.

## Teorema do Confronto {#sec-confronto}

Às vezes, alguns limites podem ser difíceis.
