lang: pt 

project:
  type: book

book:
  language: pt
  title: "Cálculo Companheiro"
  author: "Arthur H. Tomita, Eduardo Yukio G. Ishihara, Gustavo S. Garone"
  date: "12/31/9999"
  chapters:
    - index.qmd
    - summary.qmd
    - intro.qmd
    - matrizes.qmd
    - references.qmd

bibliography: references.bib
csl: associacao-brasileira-de-normas-tecnicas.csl 

format:
  html:
    theme: cosmo
    # cite-method: biblatex
  pdf:
    documentclass: scrreprt
    # cite-method: biblatex
    include-in-header:
      - text: |
          \usepackage[makeroom]{cancel}

# header-includes:
    # - \usepackage[makeroom]{cancel}


