lang: pt 

project:
  type: book
  
filters:
  - diagram
diagram:
  cache: true
  engine:
    tikz:
      header-includes:
        - '\usetikzlibrary{patterns}'

book:
  language: pt
  title: "Cálculo Companheiro"
  author: "Artur H. Tomita, Eduardo Yukio G. Ishihara, Gustavo S. Garone"
  date: last-modified
  chapters:
    - index.qmd
    - prefacio.qmd
    - part: "Bem-Vindo!"
      chapters:
        - intro.qmd
    - part: "Matemática Elementar"
      chapters:
        - polinomios.qmd
        - matrizes.qmd
    - part: "Introdução ao Cálculo"
      chapters:
        - weierstrass.qmd
    - part: "Aplicações do Cálculo"
    - part: "Álgebra Linear"
      chapters:
        - espacos-vetoriais.qmd
    - part: "Cálculo Multivariado"
      chapters:
        - curvas.qmd
        - limites-multivariados.qmd
        - d-gradiente.qmd
        - d-ordem-superior.qmd
        - taylor-multi.qmd
        - mins-maxs.qmd
    - references.qmd

bibliography: references.bib
csl: associacao-brasileira-de-normas-tecnicas.csl 

format:
  html:
    theme: cosmo
    # cite-method: biblatex
    extract-media: ./tikzdesigns/
  pdf:
    documentclass: scrreprt
    cite-method: biblatex
    include-in-header:
      text: |
        \usepackage[makeroom]{cancel}
        \usepackage{makeidx}
        \makeindex
    include-after-body:
      text: |
        \printindex

# header-includes:
    # - \usepackage[makeroom]{cancel}


