# Introdução

## Apresentação do material

Bom dia, boa tarde, boa noite e, para os desesperados, boa madrugada! 👋

Este material de apoio aos estudo e preparação para as disciplinas de Cálculo I e II foi financiado pelo [Programa Unificado de Bolsas](https://prip.usp.br/pub/)
como um projeto de ensino do [Professor Dr. Artur Hideyuki Tomita](https://www.ime.usp.br/~tomita/) e produzido pelos discentes
[Gustavo Silva Garone](gustavo.garone@usp.br) e [Eduardo Yukio G. Ishihara](eduardoyukio.ishihara@usp.br), ambos do
Instituto de Matemática e Estatística (:red_circle: :white_circle: ). Por favor, sinta-se livre para enviar-nos um e-mail
com correções, recomendações, elogios ou críticas. Este projeto está constantemente sendo produzido, mantido e corrigido,
então ficaremos mais do que felizes em receber sua opinião.

Independentemente se este é o seu primeiro ano ou não da faculdade, muito provavelmente já ouviu atrocidades sobre
~~o terror dos cursos de exatas~~ Cálculo Diferencial e Integral. É exatamente por conta dessa mística construída ao
redor de uma das disciplinas mais fundamentais para a matemática que nasce o projeto. Somos estudantes fazendo um material
para estudantes (sob a supervisão de um professor), o que nos dá uma visão muito mais próxima da real experiência que você,
leitor, provavelmente está passando agora. Buscamos o equilíbrio entre o rigor exigido pelo fazer matemático e a
informalidade que gera interesse.

Para todos os tópicos, tentaremos apresentá-los seguindo uma sequência lógica e didática composta por uma introdução
fundamentada na sua intuição, algumas aplicações reais do tópico para os diversos cursos, introdução à teoria, formalização
da teoria, formalização dos exemplos, alguns exercícios de apoio e, por fim, soluções comentadas. Uma segunda característica
notável no material é a divisão dos temas em "importantes" e "opcionais". Por mais que sejamos obrigados a dizer que todos
os tópicos da matéria são igualmente importantes em sua íntegra, alguns terão menor aplicações e outros serão frequentemente
requeridos em matérias futuras. Por fim, sempre que possível, apresentaremos interpretações alternativas aos conceitos debatidos
em cada tópico. Por exemplo, no estudo do determinante de matrizes, trataremos os determinantes primeiro como uma construção
algébrica, pois, apesar de abstrato, é mais direto e é o mínimo necessário para a sua aplicação, apesar de raso, e, em seguida,
apresentaremos o determinante sob uma perspectiva geométrica, que é um primeiro contato com a algebra linear e as transformações lineares.

## Estudando Matemática

Se você é do IME, este tópico provavelmente estendê-se-á a quase todas as outras matérias, mas, para os outros institutos,
o estudo rigoros da matemática pode ser um tópico exótico até agora. Uma parte significativa dos docentes diria que as
notas devem ser a menor preocupação do aluno e que o verdadeiro objetivo da disciplina é aprender o conteúdo e, se possível,
divertir-se no processo, mas sabemos que tal realidade é muito distante para quase todos nós meros mortais.
A primeira caractarística notável que você pode notar na matemática é que é impossível decorar tudo que pode cair numa prova