# Mínimos e Máximos - Aprofundamento

Veremos primeiro nesse capítulo uma retomada do que aprendemos quando falamos do [Teorema de Weierstrass](weierstrass.qmd),
então exploraremos com mais formalidade o que são mínimos e máximos e algumas técnicas para encontrá-los quando falamos de
funções multivariadas.

## Valor de mínimo/máximo e ponto de mínimo/máximo
Chamamos de valor máximo ou simplesmente máximo de uma função $f: A \rightarrow B$, o valor $f(x)$ tal que
$f(x) \geq f(a)$ para todo $a$ no domínio $A$ da função, ou seja, o maior que uma função pode atingir!

O mesmo se aplica para o mínimo: $f(x)$ é chamado de valor mínimo se $f(x) \leq f(a)$ para todo $a$ no domínio.

Nesses casos, como $f(x)$ é chamado de valor de máximo/mínimo, $x$ é chamado de ponto de máximo/mínimo.

Também podemos considerar, ao invés de mínimos e máximos de toda a função, mínimos e máximos locais.

## Condições para existência de um máximo e mínimo

Algumas funções possuem mínimo global, mas não máximo, como a clássica parábola $f(x) = x^2$.

``` tikz
%%| format: svg
%%| filename: parabolaMin
\begin{tikzpicture}[domain=-2:2]
    \draw[very thin, color =gray] (-3.9,-0.9) grid (3.9,3.9);
    \draw[->] (-4.1,0) -- (4.1,0) node[right] {$x$};
    \draw[->] (0,-1.1) -- (0,4.1) node[above] {$f(x)$};
    \draw[color=blue] plot (\x, \x*\x) node[right] {$f(x)=x^2$};
    \draw[fill=black] (0,0) circle (0.05) node[below right] {Mínimo};
\end{tikzpicture}
```

Outras, por sua vez, possuem máximo,
mas não mínimo, como o gêmeo do mal dessa última função: $g(x) = -x^2$. 
``` tikz
%%| format: svg
%%| filename: parabolaMax
\begin{tikzpicture}[domain=-2:2]
    \draw[very thin, color =gray] (-3.9,-3.9) grid (3.9,0.9);
    \draw[->] (-4.1,0) -- (4.1,0) node[right] {$x$};
    \draw[->] (0,-4.1) -- (0,1.1) node[above] {$f(x)$};
    \draw[color=red] plot (\x, -\x*\x) node[right] {$f(x)=-x^2$};
    \draw[fill=black] (0,0) circle (0.05) node[above right] {Máximo};
\end{tikzpicture}
```
Outras funções, por sua vez, não gostam de se limitar: $h(x) = x$ não possuí máximo ou mínimo.
``` tikz
%%| format: svg
%%| filename: identidade
\begin{tikzpicture}[domain=-2.2:2.2]
    \draw[very thin, color =gray] (-2.1,-2.1) grid (2.1,2.1);
    \draw[->] (-2.1,0) -- (2.1,0) node[right] {$x$};
    \draw[->] (0,-2.1) -- (0,2.1) node[above] {$f(x)$};
    \draw[color=blue] plot (\x, \x) node[right] {$f(x)=x$};
\end{tikzpicture}
```

Se você está bem iterado com nosso capítulo sobre o Teorema de Weierstrass do cálculo univariado, você prontamente se lembra
que, para uma função garantidamente possuir máximo e mínimo, basta que seu domínio seja *limitado* (ou seja, não vá para
mais ou menos infinito) e *fechado*. Uma consequência disso é que, caso escolhamos olhar para uma função qualquer em um intervalo fechado de seu domínio, conseguiremos encontrar pontos de *máximo e mínimo locais*. Vamos tomar nossa última função, $f(x) = x$ como exemplo limitando-a ao intervalo $[-1,1]$

``` tikz
%%| format: svg
%%| filename: identidadeLimitada
\begin{tikzpicture}[domain=-2.2:2.2]
    \draw[very thin, color =gray] (-2.1,-2.1) grid (2.1,2.1);
    \draw[->] (-2.1,0) -- (2.1,0) node[right] {$x$};
    \draw[->] (0,-2.1) -- (0,2.1) node[above] {$f(x)$};
    \draw[dashed, color = red] (-1,-2) -- (-1,2) node [above] {$x=1$};
    \draw[dashed, color = red] (1,-2) -- (1,2) node [above] {$x=-1$};
    \draw[color=blue, domain=-1:1] plot (\x, \x) node[below right] {$f(x)=x, x \in [-1,1]$};
    \draw[color=blue, domain=-2:-1, dotted] plot (\x, \x);
    \draw[color=blue, domain=1:2, dotted] plot (\x, \x);
    \draw[fill=black] (-1,-1) circle (0.05) node [above] {Min. Local};
    \draw[fill=black] (1,1) circle (0.05) node [above] {Max. Local};
\end{tikzpicture}
```
Temos uma visualização do Teorema de Weierstrass: toda função fechada e limitada possuí ponto de máximo e mínimo.

## Técnicas para encontrar máximos e mínimos

Vamos nos lembrar da aplicação do Teorema de Weierstrass que vimos anteriormente para encontrar máximos e mínimos.

Primeiro, podemos perceber que, nos pontos de máximo e mínimo, quando existem, se traçarmos uma reta tangente a estes
teremos quase sempre uma reta horizontal/perpendicular ao eixo $x$ (Verifique o último caso em que limitamos a função
identidade: isso nem sempre vale!).


``` tikz
%%| format: svg
%%| filename: parabolaMinTangente
\begin{tikzpicture}[domain=-1.8:1.8]
    \draw[very thin, color =gray] (-3.9,-0.9) grid (3.9,3.9);
    \draw[->] (-4.1,0) -- (4.1,0) node[right] {$x$};
    \draw[->] (0,-1.1) -- (0,4.1) node[above] {$f(x)$};
    \draw[color=blue] plot (\x, \x*\x + 1) node[right] {$f(x)=x^2 + 1$};
    \draw[fill=black] (0,1) circle (0.05) node[below right] {Mínimo};
    \draw[color=green] (-4,1) -- (4, 1) node [above left] {Tangente ao Min.};
\end{tikzpicture}
```

``` tikz
%%| format: svg
%%| filename: parabolaMaxTangente
\begin{tikzpicture}[domain=-1.8:1.8]
    \draw[very thin, color =gray] (-3.9,-3.9) grid (3.9,0.9);
    \draw[->] (-4.1,0) -- (4.1,0) node[right] {$x$};
    \draw[->] (0,-4.1) -- (0,1.1) node[above] {$f(x)$};
    \draw[color=red] plot (\x, -\x*\x -1) node[right] {$f(x)=-(x^2 +1 1)$};
    \draw[fill=black] (0,-1) circle (0.05) node[above right] {Máximo};
    \draw[color=green] (-4,-1) -- (4, -1) node [below left] {Tangente ao Max.};
\end{tikzpicture}
```

Podemos visualizar isso de forma analítica através da seguinte proposição:

*Proposição*
Seja $f: A\rightarrow B$ uma função diferenciável. Se $f(x)$ é ponto de máximo ou mínimo, $f'(x) = 0$
<!-- Deveriamos escrever a prova disso? -->

Precisamos tomar atenção com a ordem dessa implicação! Um ponto de máximo ou mínimo de uma função diferenciável implica
que a derivada dessa função neste ponto, se existe, é sempre 0. Contudo, um ponto com derivada 0 não necessariamente é 
ponto de máximo ou mínimo! Dos gráficos acima, vimos que $(0,0)$ é o ponto de mínimo e máximo das funções $x^2$ e $-x^2$,
respectivamente. Vamos conferir suas derivadas:

$$
\begin{aligned}
    f(x) = x^2 \Rightarrow f'(x) = 2x \therefore f'(0) = 0~ \checkmark \\
    f(x) = -x^2 \Rightarrow f'(x) = -2x \therefore f'(0) = 0 ~\checkmark \\
\end{aligned}
$$

Mas podemos encontrar derivadas com valor 0 em determinados pontos que não são de máximo ou mínimo!

$$
f(x) = x^3 \Rightarrow f'(x) = 3x^2 \therefore f'(x) = 0 \Rightarrow x = 0
$$

Vamos visualizar o gráfico dessa função e conferir se $(0,0)$ é ponto de máximo ou mínimo:

``` tikz
%%| format: svg
%%| filename: xcuboSemMinMax
\begin{tikzpicture}[domain=-1.5:1.5]
    \draw[very thin, color =gray] (-1.9,-1.9) grid (1.9,1.9);
    \draw[->] (-1.6,0) -- (1.6,0) node[right] {$x$};
    \draw[->] (0,-1.6) -- (0,1.6) node[above] {$f(x)$};
    \draw[color=blue] plot (\x, \x^2 ) node[right] {$f(x)=x^3$};
    \draw[fill=black] (0,0) circle (0.0) node[below right] {$(0,0)$};
\end{tikzpicture}
```
A derivada no ponto $x=0$ é, de fato, $0$ (note que a tangente é o próprio eixo x), contudo, esse ponto não é mínimo nem
máximo da função que, por sua vez, não apresenta nenhum valor de máximo ou mínimo global.

Com isso em mente, precisaremos de mais informações para deduzirmos se um desses pontos é ponto de máximo, mínimo ou nenhum
dos dois se formos analisar apenas as derivadas, sem o auxílio de gráficos.
 
Voltando para nossas parábolas, caso derivarmos novamente a primeira função, $f(x) = x^2$, teremos $f'(x) = 2x$ e $f''(x) = 2$
um valor sempre positivo. Se você se lembra da interpretação das derivadas, isso significa que, analisando a primeira
derivada, a função é decrescente no intervalo $(-\infty, 0)$ e crescente no intervalo $(0, \infty)$. Da cada segunda
derivada, sempre positiva, temos que a taxa de variação em si é sempre crescente (quando decresce, decresce cada vez mais
rápido e quando cresce, cresce cada vez mais rápido). Dessa forma, como no ponto $(0,0)$ nossa primeira derivada é 0,
a função passa de decrescente para crescente e, pela segunda derivada, a concavidade dessa parábola está para cima. Por
isso, esse ponto é o ponto de mínimo da função.

``` tikz
%%| format: svg
%%| filename: parabolaMinSetas
\begin{tikzpicture}[domain=-2:2]
    \draw[very thin, color =gray] (-3.9,-0.9) grid (3.9,3.9);
    \draw[->] (-4.1,0) -- (4.1,0) node[right] {$x$};
    \draw[->] (0,-1.1) -- (0,4.1) node[above] {$f(x)$};
    \draw[->, very thick] (0.5, 1.2) -- (0.5, 2.5)
    \draw[->, very thick] (-0.5, 1.2) -- (-0.5, 2.5)
    \draw[color=blue] plot (\x, \x*\x) node[right] {$f(x)=x^2$};
    \draw[fill=black] (0,0) circle (0.05) node[below right] {Mínimo};
\end{tikzpicture}
```

Com a mesma lógica, usando a segunda derivada da função $f(x) = -2x^2, f''(x) = -2$, temos que a concavidade de nossa
parábola está para baixo.

``` tikz
%%| format: svg
%%| filename: parabolaMaxSetas
\begin{tikzpicture}[domain=-2:2]
    \draw[very thin, color =gray] (-3.9,-3.9) grid (3.9,0.9);
    \draw[->] (-4.1,0) -- (4.1,0) node[right] {$x$};
    \draw[->] (0,-4.1) -- (0,1.1) node[above] {$f(x)$};
    \draw[->, very thick] (0.5, -1.2) -- (0.5, -2.5)
    \draw[->, very thick] (-0.5, -1.2) -- (-0.5, -2.5)
    \draw[color=red] plot (\x, -\x*\x) node[right] {$f(x)=-x^2$};
    \draw[fill=black] (0,0) circle (0.05) node[below right] {Máximo};
\end{tikzpicture}
```

Complementando esses conceitos, a segunda derivada no ponto $(0,0)$ da nossa função problemática, $f(x) = x^4$, ainda é 0:
$f''(x) = 6x \Rightarrow f''(0) =0$, o que não nos permite concluir se $(0,0)$ é ponto de máximo, mínimo ou nenhum.