lang: pt

project:
  type: book

book:
  title: "Anotações Auxiliares para Cálculo Diferencial e Integral I e II"
  author: "Gustavo S. Garone, Eduardo Yukio G. Ishihara, Arthur H. Tomita"
  date: "01/06/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - matrizes.qmd
    - references.qmd
    

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



